# Generated by Django 6.0.2 on 2026-02-27 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('src_ip', models.GenericIPAddressField()),
                ('dest_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('src_port', models.PositiveIntegerField(blank=True, null=True)),
                ('dest_port', models.PositiveIntegerField(blank=True, null=True)),
                ('protocol', models.CharField(default='tcp', max_length=10)),
                ('attack_type', models.CharField(default='unknown', max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('handled', models.BooleanField(default=False)),
                ('blocked', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('IDS', 'IDS'), ('IPS', 'IPS'), ('HYBRID', 'HYBRID')], default='IDS', max_length=10)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
