# Generated by Django 6.0.4 on 2026-04-20 12:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='mode_at_detection',
            field=models.CharField(choices=[('IDS', 'IDS'), ('IPS', 'IPS'), ('HYBRID', 'HYBRID')], default='IDS', max_length=10),
        ),
        migrations.AddField(
            model_name='alert',
            name='response_action',
            field=models.CharField(choices=[('alerted', 'Alerted'), ('watched', 'Watched'), ('blocked-auto', 'Blocked Automatically'), ('blocked-manual', 'Blocked Manually'), ('blocked-existing', 'Blocked By Existing Rule')], default='alerted', max_length=30),
        ),
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.CharField(default='kafka', max_length=30),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='attack_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='block_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='last_blocked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='last_unblocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='source',
            field=models.CharField(default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='SecurityAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_type', models.CharField(choices=[('BLOCK', 'Block'), ('UNBLOCK', 'Unblock'), ('MODE_CHANGE', 'Mode Change'), ('AUTOMATION', 'Automation')], max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic'), ('system', 'System'), ('kafka', 'Kafka'), ('api', 'API')], default='system', max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('mode', models.CharField(blank=True, choices=[('IDS', 'IDS'), ('IPS', 'IPS'), ('HYBRID', 'HYBRID')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('attack_type', models.CharField(blank=True, max_length=100)),
                ('severity', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(default='success', max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_actions', to='dashboard.alert')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
    ]
