# Generated by Django 6.0.4 on 2026-04-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alert_mode_at_detection_alert_response_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuricataRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_id', models.CharField(max_length=64, unique=True)),
                ('sid', models.PositiveIntegerField(unique=True)),
                ('msg', models.CharField(max_length=255)),
                ('action', models.CharField(default='alert', max_length=20)),
                ('proto', models.CharField(default='tcp', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('comment', models.TextField(blank=True)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('raw_rule', models.TextField()),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed'), ('local-only', 'Local Only')], default='pending', max_length=20)),
                ('last_sync_error', models.TextField(blank=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sid', 'created_at'],
            },
        ),
    ]
