# Generated by Codex on 2026-04-23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_suricatarule"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemconfig",
            name="next_rule_sid",
            field=models.PositiveIntegerField(default=1000001),
        ),
        migrations.CreateModel(
            name="OldAlertLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("archived_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("archive_batch_id", models.CharField(db_index=True, max_length=36)),
                ("archive_reason", models.CharField(default="manual-admin", max_length=40)),
                ("archived_by", models.CharField(blank=True, max_length=150)),
                ("original_alert_id", models.PositiveIntegerField(db_index=True)),
                ("original_timestamp", models.DateTimeField(db_index=True)),
                ("src_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("dest_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("src_port", models.PositiveIntegerField(blank=True, null=True)),
                ("dest_port", models.PositiveIntegerField(blank=True, null=True)),
                ("protocol", models.CharField(default="tcp", max_length=10)),
                ("attack_type", models.CharField(default="unknown", max_length=100)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("handled", models.BooleanField(default=False)),
                ("blocked", models.BooleanField(default=False)),
                (
                    "mode_at_detection",
                    models.CharField(
                        choices=[("IDS", "IDS"), ("IPS", "IPS"), ("HYBRID", "HYBRID")],
                        default="IDS",
                        max_length=10,
                    ),
                ),
                ("response_action", models.CharField(default="alerted", max_length=30)),
                ("source", models.CharField(default="kafka", max_length=30)),
                ("payload", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-archived_at", "-original_timestamp", "-id"],
            },
        ),
    ]
