"""
Django settings for IDSIPS project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import json
import os
import secrets
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv():
    env_path = BASE_DIR / ".env"
    if not env_path.exists():
        return
    for raw_line in env_path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ.setdefault(key, value)


_load_dotenv()


def _env(name, default=""):
    value = os.environ.get(name)
    return default if value in (None, "") else value


def _env_bool(name, default=False):
    value = os.environ.get(name)
    if value in (None, ""):
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_list(name, default=None):
    value = os.environ.get(name)
    if value in (None, ""):
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret.
DEBUG = _env_bool("DJANGO_DEBUG", True)

SECRET_KEY = _env("DJANGO_SECRET_KEY")
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY must be set when DJANGO_DEBUG=False.")
    SECRET_KEY = secrets.token_urlsafe(50)

ALLOWED_HOSTS = _env_list(
    "DJANGO_ALLOWED_HOSTS",
    ["localhost", "127.0.0.1", "[::1]", "testserver"],
)
CSRF_TRUSTED_ORIGINS = _env_list("DJANGO_CSRF_TRUSTED_ORIGINS")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'dashboard.middleware.SecurityHeadersMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'IDSIPS.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'IDSIPS.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': _env("DJANGO_SQLITE_PATH", BASE_DIR / 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = _env("DJANGO_REFERRER_POLICY", "same-origin")
SECURE_SSL_REDIRECT = _env_bool("DJANGO_SECURE_SSL_REDIRECT", False)
SECURE_HSTS_SECONDS = int(_env("DJANGO_SECURE_HSTS_SECONDS", "0") or "0")
SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS", False)
SECURE_HSTS_PRELOAD = _env_bool("DJANGO_SECURE_HSTS_PRELOAD", False)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = _env("DJANGO_SESSION_COOKIE_SAMESITE", "Lax")
SESSION_COOKIE_SECURE = _env_bool("DJANGO_SESSION_COOKIE_SECURE", SECURE_SSL_REDIRECT)
CSRF_COOKIE_HTTPONLY = _env_bool("DJANGO_CSRF_COOKIE_HTTPONLY", True)
CSRF_COOKIE_SAMESITE = _env("DJANGO_CSRF_COOKIE_SAMESITE", "Lax")
CSRF_COOKIE_SECURE = _env_bool("DJANGO_CSRF_COOKIE_SECURE", SECURE_SSL_REDIRECT)

CONTENT_SECURITY_POLICY = _env(
    "DJANGO_CONTENT_SECURITY_POLICY",
    "default-src 'self'; "
    "script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; "
    "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://cdnjs.cloudflare.com; "
    "font-src 'self' https://fonts.gstatic.com https://cdnjs.cloudflare.com data:; "
    "img-src 'self' data:; "
    "connect-src 'self'; "
    "frame-ancestors 'none'; "
    "base-uri 'self'; "
    "form-action 'self'",
)
PERMISSIONS_POLICY = _env(
    "DJANGO_PERMISSIONS_POLICY",
    "camera=(), microphone=(), geolocation=(), payment=(), usb=()",
)
CROSS_ORIGIN_OPENER_POLICY = _env("DJANGO_CROSS_ORIGIN_OPENER_POLICY", "same-origin")

DASHBOARD_REQUIRE_STAFF_FOR_MUTATIONS = _env_bool(
    "DASHBOARD_REQUIRE_STAFF_FOR_MUTATIONS",
    False if DEBUG else True,
)
DASHBOARD_REQUIRE_STAFF_FOR_READ_APIS = _env_bool("DASHBOARD_REQUIRE_STAFF_FOR_READ_APIS", False)
DASHBOARD_REQUIRE_INGEST_TOKEN = _env_bool("DASHBOARD_REQUIRE_INGEST_TOKEN", False if DEBUG else True)
IDS_INGEST_API_TOKEN = _env("IDS_INGEST_API_TOKEN")

KAFKA_BOOTSTRAP_SERVERS = _env("KAFKA_BOOTSTRAP_SERVERS", "10.114.98.28:9092")
KAFKA_ALERT_TOPIC = _env("KAFKA_ALERT_TOPIC", "ids-alerts")
KAFKA_CONSUMER_GROUP = _env("KAFKA_CONSUMER_GROUP", "ids-dashboard")
KAFKA_AUTO_OFFSET_RESET = _env("KAFKA_AUTO_OFFSET_RESET", "earliest")
KAFKA_ENABLE_AUTO_COMMIT = _env_bool("KAFKA_ENABLE_AUTO_COMMIT", True)
KAFKA_SECURITY_PROTOCOL = _env("KAFKA_SECURITY_PROTOCOL")
KAFKA_SASL_MECHANISM = _env("KAFKA_SASL_MECHANISM")
KAFKA_SASL_USERNAME = _env("KAFKA_SASL_USERNAME")
KAFKA_SASL_PASSWORD = _env("KAFKA_SASL_PASSWORD")

def _load_suricata_profile():
    profile = {}
    for name in ("suricata_remote.json", "suricata_remote.local.json"):
        path = BASE_DIR / name
        if not path.exists():
            continue
        try:
            profile.update(json.loads(path.read_text(encoding="utf-8")))
        except Exception:
            continue
    return profile


SURICATA_PROFILE = _load_suricata_profile()
DEFAULT_SURICATA_KEY_PATH = str((BASE_DIR / "ssh.txt").resolve()) if (BASE_DIR / "ssh.txt").exists() else ""


def _cfg(name, default=""):
    env_value = os.environ.get(name)
    if env_value not in (None, ""):
        return env_value
    return SURICATA_PROFILE.get(name.lower(), default)


SURICATA_SSH_HOST = str(_cfg("SURICATA_SSH_HOST", "")).strip()
SURICATA_SSH_PORT = int(str(_cfg("SURICATA_SSH_PORT", "22")).strip() or "22")
SURICATA_SSH_USER = str(_cfg("SURICATA_SSH_USER", "")).strip()
SURICATA_SSH_PASSWORD = str(_cfg("SURICATA_SSH_PASSWORD", "")).strip()
SURICATA_SSH_KEY_PATH = str(_cfg("SURICATA_SSH_KEY_PATH", DEFAULT_SURICATA_KEY_PATH)).strip()
SURICATA_SSH_KNOWN_HOSTS = str(_cfg("SURICATA_SSH_KNOWN_HOSTS", "")).strip()
SURICATA_SSH_ALLOW_UNKNOWN_HOSTS = _env_bool("SURICATA_SSH_ALLOW_UNKNOWN_HOSTS", False)

SURICATA_REMOTE_RULES_DIR = str(_cfg("SURICATA_REMOTE_RULES_DIR", "/etc/suricata/rules")).strip()
SURICATA_REMOTE_CUSTOM_RULES_FILE = str(_cfg("SURICATA_REMOTE_CUSTOM_RULES_FILE", "dashboard_custom.rules")).strip()
SURICATA_REMOTE_BLOCK_RULES_FILE = str(_cfg("SURICATA_REMOTE_BLOCK_RULES_FILE", "dashboard_block.rules")).strip()
SURICATA_REMOTE_RELOAD_COMMAND = str(
    _cfg("SURICATA_REMOTE_RELOAD_COMMAND", "sudo suricatasc -c ruleset-reload-nonblocking")
).strip()
SURICATA_REMOTE_VALIDATE_COMMAND = str(
    _cfg("SURICATA_REMOTE_VALIDATE_COMMAND", "")
).strip()
SURICATA_HOME_NET = str(_cfg("SURICATA_HOME_NET", "$HOME_NET")).strip() or "$HOME_NET"
SURICATA_SYNC_ENABLED = bool(
    SURICATA_SSH_HOST
    and SURICATA_SSH_USER
    and (SURICATA_SSH_KEY_PATH or SURICATA_SSH_PASSWORD)
)
